spring:
  application:
    name: Kafka-Solutions
  kafka:
    ssl:
      trust-store-path: src\main\resources\kafka.truststore.jks
      trust-store-location: file:${spring.kafka.ssl.trust-store-path}
      trust-store-password: secret
    jaas:
      enabled: true
      login-module: org.apache.kafka.common.security.plain.PlainLoginModule
      control-flag: required
      options:
        username: admin
        password: admin-secret
      config-string: ${spring.kafka.jaas.login-module} ${spring.kafka.jaas.control-flag} username=${spring.kafka.jaas.options.username} password=${spring.kafka.jaas.options.password};
    template:
      default-topic: dev-topic
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: ${spring.kafka.jaas.config-string}
    admin:
      fail-fast: true
server:
  port: 8082
